---
    name: Compile Develop Brench

    on:
      push:
        branches:
          - main
        tags:
          - "*"
      pull_request:
        branches:
          - main
      workflow_dispatch:
        inputs:
          board:
            description: 'Board to Compile'
            type: choice
            required: true
            default: 'M5Cardputer'
            options: ['M5Cardputer', 'M5StickCPlus2', 'M5StickCPlus', 'M5StickC']
      
    jobs:
      compile_sketch:
        name: Build ${{ matrix.board.name }}
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
          matrix:
            locale:
              - en-us
              - pt-br
            board:
              - {
                  name: "M5Cardputer",
                  env: "m5stack-cardputer",
                  partitions: {
                    bootloader_addr: "0x0000",
                  },
                }
              - {
                  name: "M5StickCPlus2",
                  env: "m5stack-cplus2",
                  partitions: {
                    bootloader_addr: "0x1000",
                  },
                }
              - {
                  name: "M5StickCPlus",
                  env: "m5stack-cplus1_1",
                  partitions: {
                    bootloader_addr: "0x1000",
                  },
                }
        #     - {
        #         name: "M5StickC",
        #         env: "m5stack-c",
        #         partitions: {
        #           bootloader_addr: "0x1000",
        #         },
        #       }
        steps:
            - uses: actions/checkout@v4
            
            - id: build
              name: setup Python
              uses: actions/setup-python@v2
              with:
                python-version: "3.x"
            
            - name: Install dependencies
              run: | 
                pip install requests esptool
            
            - name: Install PlatformIO Core
              run: |
                pip install platformio
                platformio update
            - name: Setup PlatformIO for Deauth
              run: |                
                pio pkg install -p espressif32 -t toolchain-xtensa32
                chmod +x deauth_setup.h
                ./deauth_setup.h
            
            - name: Run Compile
              run: | 
                plarformio run -e ${{ matrix.board.env }}

            - name: Merge files
              run: | 
                esptool.py --chip esp32s3 merge_bin -o Bruce_${{ matrix.board.env }}_${{ github.run_number }}.bin \
                  ${{ matrix.board.partitions.bootloader_addr }} .pio/build/${{ matrix.board.env }}/bootloader.bin \
                  0x8000 .pio/build/${{ matrix.board.env }}/partitions.bin \
                  0x10000 .pio/build/${{ matrix.board.env }}/firmware.bin

            - name: Upload ${{ matrix.board.name }}
              uses: actions/upload-artifact@v4
              with:
                name: Bruce_${{ matrix.board.env }}_${{ github.run_number }}
                path: Bruce_*.bin
                retention-days: 5
                if-no-files-found: error
